language: node_js
node_js:
  - stable
  - '0.12'
sudo: false
services:
  - rabbitmq
deploy:
  provider: npm
  email: pattyn.kurt@gmail.com
  api_key:
    secure: L1U5U0yQ76sorYtrz51bWAUhj43Muarveju+mUve0UPeeDvXJ9lnc+m9pRnYsK0QbfPRqWOolLp1Sr4QhR3DRUABmaWDtyPR3sdZN0PAegI3JwZ1QLEEIG/iM9I7IaCMiX6gEuelXNcYkOmJ58ZePv2tYc78p4j+K4/ejfqwbWzWGtxluvqXzD8J2+hv6jNU0vKgPnfhxq+/olddNAk9+pP8Th06nGGAPSXhTREkU33QBiRVuT1n4q9LxAHGgEKLMMVamgsy6JnwXfm/V08bWe/GGWxTpwJdJoIAX3crwNj0u/joCslkv4vDRb/Rueup5xf9gCbsqPp/jp74dtPJBHBIOm1y6NM3LtYCO9Uj8498BJB/0ZFbBNFsIW8H/SAPkg8guknNynNy7W0MHm3TtVrW3Vv8ykga7rVeaQvp8OL3yQFUSl12UFeOOixQxLeJ0LaRzW6wyg4dUu6cOC86sGKyyqgHzufihaaex37YPjAj5Mvnd1PLZ5EM6JUZnB1+zBrUT0x2Ypa1BVEyKafw+iYMgJ6a+HYJTc7LzFVBQObB9dR8sAH0dRELIeVGaGVvPeYbSXudMTGflGDtWfNJBoSEniOCG/YbpQ+uTM03bpIBV1wetPsywrZS65klduc+NVyog5NincoFyIE52miJSHwbDAScGmMY5H26ibmkTA0=
  on:
    tags: true
    repo: KurtPattyn/krew
    branch: master
addons:
  code_climate:
    repo_token:
      secure: xSNouvxZlek5ONJJGtd1qoUzWqbMtxf0DwAN4hhKaOgmHFp3vBCFw+LrKMFq1VODAv+ACGiyWuTw8h8AzigR3vDQKxUgJ5iH+Jylp21izCwED84soYf7gJXn08FMEk/WyJBP9Qgk9ON+tfTAioZhrTk3ENZc/Wfm8u1o/0PKj2eE2AcAHMQPnxPksk8gyy+WSMHkw1FyqTnl38qZERGf08BPepWkaoVkRnnmwc6pUdU/KZpmRGcfZmGX+2qBGZhOXaP+73pe7vBseSiePgqGvUn5rPWhU5/9eGBKLqQz6M0yV8xkMOh7RHie6jGiHtY3BJoyJD5GkMh4sk8+EIfQgyaPneXlAcxVyHNj5nj2Znu6E0cKy+U7J41SOT292/h5BcoeSc2Emx7D6lU+33ydgpGMsulckSvYr/+x4TNHNaRSsq/y27IV0LoDZQ6RJeZEy4aSVCmx+aWU2qiYpjCfy2Xs4lI3CqV8by9EutFGUGydA4Cmt93ff2X8/TFQUPAKXp8rqKs6lSPC8TXEksfKEbSIJakglgiX8EKbjLuCS1DFtEhhjJ5vrSZim6KUkwmT9G+ldI7sIjxp3tMSwGP7CfpPlC4Zs30QmkaLZf48SZ8nAzmkuAOofzMKGirYaQWVH3+GFUQ8EUKwFMNteE5SS17BFyeoCHvUH702juy9n2M=
before_script:
  - npm run check-style
  - npm run code-analysis
script:
  - npm run test-ci
  - npm run check-coverage
after_success:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
  - npm install codeclimate-test-reporter && codeclimate-test-reporter < ./coverage/lcov.info
